<a href="https://colab.research.google.com/github/alwaysalearner1234/ML02/blob/main/Save_and_load_using_pickle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Machine Learning With Python: Save And Load Trained Model**




In [18]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [19]:
df = pd.read_csv("homeprices (1).csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [20]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [21]:
model.coef_


array([135.78767123])

In [22]:
import pandas as pd
from IPython.display import display, HTML
import numpy as np

def show_feature_importance(model, feature_names):
    """
    Display model coefficients with feature names in a colorful table.
    Positive coefficients in green, negative in red.
    """
    coefs = model.coef_.flatten()  # Flatten in case of 2D array
    df = pd.DataFrame({
        "Feature": feature_names,
        "Coefficient": coefs
    })

    # Create colored HTML table
    def color_coef(val):
        color = "green" if val > 0 else "red" if val < 0 else "black"
        return f'color: {color}; font-weight: bold;'

    display(df.style.applymap(color_coef, subset=["Coefficient"]).set_caption("Feature Importance"))

# --- Example Usage ---
from sklearn.linear_model import LinearRegression

# Sample data
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
y = np.array([2, 3, 4, 5])
feature_names = ["Feature1", "Feature2"]

# Train model
model = LinearRegression()
model.fit(X, y)

# Show coefficients
show_feature_importance(model, feature_names)


/tmp/ipython-input-927411037.py:21: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  display(df.style.applymap(color_coef, subset=["Coefficient"]).set_caption("Feature Importance"))


In [23]:
from sklearn.linear_model import LogisticRegression

X = np.array([[0,1],[1,1],[2,0],[3,1]])
y = np.array([0,0,1,1])

model = LogisticRegression()
model.fit(X, y)
print(model.coef_)


[[ 0.9380273  -0.33119484]]


In [24]:
model.intercept_


array([-1.17331846])

In [25]:
import pandas as pd
from IPython.display import display, HTML
import numpy as np
from sklearn.linear_model import LinearRegression

# --- Sample Data ---
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
y = np.array([2, 3, 4, 5])
feature_names = ["Feature1", "Feature2"]

# --- Train model ---
model = LinearRegression()
model.fit(X, y)

# --- Prepare DataFrame for coefficients + intercept ---
coefs = model.coef_.flatten()
df = pd.DataFrame({
    "Feature": feature_names + ["Intercept"],
    "Value": np.append(coefs, model.intercept_)
})

# --- Function to color values ---
def color_value(val):
    if val > 0:
        return 'color: green; font-weight:bold;'
    elif val < 0:
        return 'color: red; font-weight:bold;'
    else:
        return 'color: black;'

# --- Display Table ---
display(df.style.applymap(color_value, subset=["Value"]).set_caption("Model Coefficients and Intercept"))


/tmp/ipython-input-1639844659.py:32: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  display(df.style.applymap(color_value, subset=["Value"]).set_caption("Model Coefficients and Intercept"))


In [26]:
import pandas as pd
from IPython.display import display
import numpy as np
from sklearn.linear_model import LinearRegression

# --- Sample Data ---
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
y = np.array([2, 3, 4, 5])
feature_names = ["Feature1", "Feature2"]

# --- Train model ---
model = LinearRegression()
model.fit(X, y)

# --- Prepare DataFrame ---
coefs = model.coef_.flatten()
df = pd.DataFrame({
    "Feature": feature_names + ["Intercept"],
    "Coefficient": np.append(coefs, model.intercept_)
})

# --- Sort by absolute coefficient value ---
df["Importance"] = df["Coefficient"].abs()
df = df.sort_values(by="Importance", ascending=False).drop(columns="Importance")

# --- Display with gradient color map ---
def color_map(val):
    """Green for positive, red for negative, intensity by magnitude"""
    max_val = df["Coefficient"].abs().max()
    intensity = int(255 * abs(val) / max_val)
    if val > 0:
        return f'color: rgb(0,{intensity},0); font-weight:bold;'
    elif val < 0:
        return f'color: rgb({intensity},0,0); font-weight:bold;'
    else:
        return 'color: black;'

display(df.style.applymap(color_map, subset=["Coefficient"]).set_caption("Feature Importance with Intercept"))


/tmp/ipython-input-1933157531.py:38: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  display(df.style.applymap(color_map, subset=["Coefficient"]).set_caption("Feature Importance with Intercept"))


In [27]:
# --- Imports ---
import pandas as pd
from IPython.display import display
import numpy as np
from sklearn.linear_model import LinearRegression

# --- Sample Dataset: Predicting House Prices ---
# Features: Bedrooms, Area (sqft), Distance from city (km)
X = np.array([
    [2, 800, 5],
    [3, 1000, 3],
    [4, 1500, 10],
    [3, 1200, 2],
    [5, 2000, 15]
])
y = np.array([50000, 65000, 120000, 70000, 160000])
feature_names = ["Bedrooms", "Area_sqft", "Distance_km"]

# --- Train Linear Regression Model ---
model = LinearRegression()
model.fit(X, y)

# --- Prepare DataFrame for coefficients + intercept ---
coefs = model.coef_.flatten()
df = pd.DataFrame({
    "Feature": feature_names + ["Intercept"],
    "Coefficient": np.append(coefs, model.intercept_)
})

# --- Sort by absolute importance ---
df["Importance"] = df["Coefficient"].abs()
df = df.sort_values(by="Importance", ascending=False).drop(columns="Importance")

# --- Color gradient function ---
def color_map(val):
    max_val = df["Coefficient"].abs().max()
    intensity = int(255 * abs(val) / max_val)
    if val > 0:
        return f'color: rgb(0,{intensity},0); font-weight:bold;'
    elif val < 0:
        return f'color: rgb({intensity},0,0); font-weight:bold;'
    else:
        return 'color: black;'

# --- Display Colorful Table ---
display(df.style.applymap(color_map, subset=["Coefficient"])
        .set_caption("House Price Model: Feature Importance with Intercept"))


/tmp/ipython-input-1161580203.py:46: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  display(df.style.applymap(color_map, subset=["Coefficient"])


In [30]:
# Correct number of features: Bedrooms, Area_sqft, Distance_km
# Suppose we want: Bedrooms=3, Area=5000, Distance=10
prediction = model.predict([[3, 5000, 10]])
print(prediction)


[202706.70147955]


In [32]:
model.predict([[3, 5000, 10]])

array([202706.70147955])

In [34]:
model.predict([[3, 5000, 10]])

array([202706.70147955])

**Save Model To a File Using Python Pickle**

In [35]:
import pickle


In [36]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

Load Saved Model


In [38]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [39]:
mp.coef_


array([16050.91383812,    29.09051349,  2830.72236728])

In [40]:
mp.intercept_


np.float64(-19205.831157527995)

In [42]:
mp.predict([[5000,70,7878]])


array([1.02537831e+08])

Save Trained Model Using joblib


In [44]:
# Install if not already installed
# !pip install joblib

import joblib


In [45]:
from sklearn.linear_model import LinearRegression
import numpy as np
import joblib

# Sample data
X = np.array([[1], [2], [3], [4]])
y = np.array([2, 4, 6, 8])

model = LinearRegression()
model.fit(X, y)

# Save model
joblib.dump(model, "linear_model.pkl")
print("Model saved!")


Model saved!


In [46]:
# Load model
loaded_model = joblib.load("linear_model.pkl")

# Predict
print(loaded_model.predict([[5]]))  # Works just like the original model


[10.]


In [47]:
joblib.dump(model, 'model_joblib')


['model_joblib']

Load Saved Model


In [49]:
mj = joblib.load('model_joblib')


In [50]:
mj.coef_


array([2.])

In [51]:
mj.intercept_


np.float64(0.0)

In [52]:
mj.predict([[5000]])


array([10000.])